apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: bitnami/rabbitmq:latest
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: management
        volumeMounts:
        - name: rabbitmq-claim
          mountPath: /data/rabbitmq
      volumes:
      - name: rabbitmq-claim
        persistentVolumeClaim:
          claimName: rabbitmq-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-volume
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/rabbitmq"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    persistentvolumeclaim.name: rabbitmq-claim
  name: rabbitmq-claim
spec:
  volumeName: rabbitmq-volume
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
  - name: amqp
    protocol: TCP
    port: 5672
    targetPort: amqp
  - name: management
    protocol: TCP
    port: 15672
    targetPort: management
